name: CI - Test Microservizio

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Installa docker-compose
        run: |
          sudo curl -L \
            "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      - name: Avvia i servizi con docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Esegui i test
        run: |
          docker-compose -f docker-compose.yml exec microservizio pytest
      
      - name: Cleanup finale
        run: |
          docker-compose -f docker-compose.yml down -v
